import 'dart:io';

void main(List<String> arguments) {
  if (arguments.length != 1) {
    stderr.writeln(
      'Usage: dart run tool/generate_supabase_seed.dart OUTPUT_SQL',
    );
    exitCode = 64;
    return;
  }

  final validWords = _readWords('assets/words/valid_words.txt');
  final answers = _readWords('assets/words/answers.txt');
  final missingAnswers = answers.where((word) => !validWords.contains(word));
  if (missingAnswers.isNotEmpty) {
    throw StateError(
      'Answer list contains words missing from valid_words.txt: '
      '${missingAnswers.take(10).join(', ')}',
    );
  }
  final output = StringBuffer()
    ..writeln('-- Generated by tool/generate_supabase_seed.dart. Do not edit.')
    ..writeln('begin;');

  for (final chunk in _chunks(validWords, 500)) {
    output
      ..writeln('insert into public.valid_words (word) values')
      ..writeln(chunk.map((word) => "  ('$word')").join(',\n'))
      ..writeln('on conflict (word) do nothing;');
  }

  final epoch = DateTime.utc(2026);
  for (var offset = 0; offset < answers.length; offset += 250) {
    final end = (offset + 250).clamp(0, answers.length);
    final values = <String>[];
    for (var index = offset; index < end; index++) {
      final date = epoch.add(Duration(days: index));
      final dateKey = _dateKey(date);
      values.add(
        "  ('classic-$dateKey', 'classic', '$dateKey', ${index + 1}, "
        "'${answers[index]}', 6, 1)",
      );
    }
    output
      ..writeln(
        'insert into public.puzzles '
        '(id, mode, puzzle_date, puzzle_number, answer, max_guesses, score_multiplier) values',
      )
      ..writeln(values.join(',\n'))
      ..writeln('on conflict (id) do nothing;');
  }
  output.writeln('commit;');
  File(arguments.single).writeAsStringSync(output.toString());
  stdout.writeln(
    'Wrote ${validWords.length} words and ${answers.length} puzzles.',
  );
}

List<String> _readWords(String path) => File(path)
    .readAsLinesSync()
    .where((word) => RegExp(r'^[a-z]{5}$').hasMatch(word))
    .toList(growable: false);

Iterable<List<String>> _chunks(List<String> values, int size) sync* {
  for (var start = 0; start < values.length; start += size) {
    yield values.sublist(start, (start + size).clamp(0, values.length));
  }
}

String _dateKey(DateTime date) =>
    '${date.year.toString().padLeft(4, '0')}-'
    '${date.month.toString().padLeft(2, '0')}-'
    '${date.day.toString().padLeft(2, '0')}';
